version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: Europe/Amsterdam
  allow:
  - dependency-type: direct
  - dependency-type: indirect
